// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBuM28zEHHN1GOUp8_zKiXFtNS1IFVlQvw',
    appId: '1:832341382865:web:293b7b4012d5fa8f4497f0',
    messagingSenderId: '832341382865',
    projectId: 'sujokbot',
    authDomain: 'sujokbot.firebaseapp.com',
    storageBucket: 'sujokbot.firebasestorage.app',
    measurementId: 'G-4G6PQGN085',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3AyA1Uk3ebdFRpYE7iGEpab7IPQRjxSY',
    appId: '1:832341382865:android:7f7381871c76355f4497f0',
    messagingSenderId: '832341382865',
    projectId: 'sujokbot',
    storageBucket: 'sujokbot.firebasestorage.app',
  );
}
